### ISSUE TITLE
Doesn't work anymore partially

### ISSUE THREAD

**Issue by Fleepy** [ceilingwaffle/Focusu#2]
When the game is paused it doesn't unblank my monitors, same does for when the song reaches a break. I don't know what happened, I reinstalled it and nothing worked.

**Comment by ceilingwaffle** [comment]
Looks like osu changed the way some memory signatures are stored. I'll work on a fix. Should be ready within a day.

**Comment by ceilingwaffle** [comment]
New release published - https://github.com/ceilingwaffle/Focusu/releases/tag/0.2.1
Let me know if it still doesn't work for you. 👍

**Comment by Fleepy** [comment]
awesome, thanks my guy.

**Comment by Fleepy** [comment]
Everything seems to be working fine. If I may suggest, Have focusu! output its current status to a text file in another folder of the program?
