### ISSUE TITLE
Not unblanking during breaks or pauses

### ISSUE THREAD

**Issue by flleeppyy** [ceilingwaffle/Focusu#3]
Focusu is blanking the screen when playing the map, but when the map is paused, or on a break, it will not unblank the other screen

[Video](https://dl.dropboxusercontent.com/s/jml4jkuklbe46lj/cFnpciv7vg.mp4)

**Comment by ceilingwaffle** [comment]
Fixed in 0.2.3 👍 
https://github.com/ceilingwaffle/Focusu/releases/tag/0.2.3

**Comment by flleeppyy** [comment]
Whew that was fast
